project/building/urls.py
from django.contrib import admin
from django.urls import path, include
from building import views

urlpatterns = [
    path('', views.map, name='map'),
    path('map/', views.map, name='map'),
    path('matching/', views.matching, name='matching'),
    path('<int:id>/', views.building_info, name='building_info'),
    path('<int:id>/evaluate/', views.evaluate, name='building_evaluate'),
]

project/chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='chat_index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('building/', include('building.urls')),

    path('home', views.home, name="home"),
    path('logout', views.logout, name='logout'),
    path('edit_comment/<int:post_pk>/<int:comment_pk>',views.edit_comment, name="edit_comment"),
    path('new/', views.new, name="new"),
    path('detail_url/<int:post_pk>', views.detail, name="detail"),
    path('edit_url/<int:post_pk>', views.edit, name="edit"),
    path('delete/<int:post_pk>', views.delete, name="delete"),
    path('delete_comment/<int:post_pk>/<int:comment_pk>', views.delete_comment, name="delete_comment"),
    path('chat/', include('chat.urls')),

    path('', views.start, name='start'),
    path('index', views.index, name="index"),

    path('registration/check', views.check, name='check'),
    path('registration/signup', views.signup, name='signup'),
    path('registration/setnickname/<int:user_pk>',
         views.setnickname, name='setnickname'),
    path('registration/login/', views.login, name='login'),
    path('registration/logout', views.logout, name='logout'),


    path('mypage', views.mypage, name='mypage'),
    path('mypage/editmyprofile/<int:profile_pk>',
         views.editmyprofile, name="editmyprofile"),
    path('mypage/certificationlocation/<int:profile_pk>',
         views.certificationlocation, name="certificationlocation"),
    path('mypage/certificationbuilding/<int:profile_pk>',
         views.certificationbuilding, name="certificationbuilding"),

    path('affiliate', views.affiliate, name="affiliate"),
    path('affiliate_detail', views.affiliate_detail, name="affiliate_detail"),

    path('building', views.building, name="building"),
    path('info', views.info, name="info"),
    path('share', views.share, name="share"),
    path('share_detail', views.share_detail, name="share_detail"),
    path('talk', views.talk, name="talk"),

]

project/building/models.py
from django.db import models
from django.contrib.auth.models import User
from app.models import Profile
from django.dispatch import receiver

# Create your models here.
class Building(models.Model):
    residents = models.ManyToManyField(Profile, blank=True, related_name="residences", through='Live')
    location_str = models.CharField(max_length=50)
    loc_latitude = models.FloatField(default=1)
    loc_longitude = models.FloatField(default=1)
    score = models.FloatField(default=0)

    def __str__(self):
        return 'id: %d / loc: %s / score: %s' % (self.id, self.location_str, self.score)


class BuildingScore(models.Model):
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    evaluated_by = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField() 


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    content = models.CharField(max_length=30, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Live(models.Model):
    residence = models.ForeignKey(Profile, on_delete=models.CASCADE)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s lives in %s' % (self.residence.username, self.building)

project/building/views.py
from django.shortcuts import render, redirect
from building.models import Building, Review, BuildingScore
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import json

# Create your views here.
def map(request):
    return render(request, 'building/map.html')


def building_info(request, id):
    building = Building.objects.get(id=id)
    reviews = Review.objects.filter(building=id) 
    return render(request, 'building/building_info.html', {'building': building, 'reviews': reviews})


def evaluate(request, id):
    building = Building.objects.get(id=id)
    if request.method == "POST":
        content = request.POST['review-content']
        score = request.POST['review-score']

        # 0~5를 벗어난 범위의 점수를 입력하면 에러 발생
        if (int(score) > 5) or (int(score) < 0):
            error = '0~5 사이의 점수를 입력해주세요!'
            return render(request, 'building/evaluate.html', {'building': building, 'error': error})

        # 우선 리뷰를 만들고
        Review.objects.create(
            user = request.user, building = building, content = content
        )

        # 건물 평점을 업데이트
        # 1. 건물 평점 모델을 생성하고
        BuildingScore.objects.create(
            building = building, evaluated_by = request.user, score = score
        )
        # 2. 건물 평점 모델 중 해당 건물과 관련된 평점의 갯수를 받아서
        score_lists = BuildingScore.objects.all().filter(building = building)
        cnt = score_lists.count()
        score_sum = 0

        # 3. 평점 평균 계산하고 평점 업데이트
        for score in score_lists:
            score_sum += score.score
        score_avg = round((score_sum / cnt), 1)
        
        building.score = score_avg
        building.save()
        return redirect('/building/' + str(id))
    return render(request, 'building/evaluate.html', {'building': building}) 


@csrf_exempt
def matching(request):
    request_body = json.loads(request.body)
    print(request.body)
    building_loc = request_body['location']
    loc_latitude = request_body['latitude']
    loc_longitude = request_body['longitude']
    try:
        building_already = Building.objects.get(location_str = building_loc)
    except:
        Building.objects.create(
            location_str = building_loc, score = 0, loc_latitude = loc_latitude, loc_longitude = loc_longitude
        )
    
    response = {
        "bid": building_already.id,
    }
    return HttpResponse(json.dumps(response))



 

project/building/templates/building/building_info.html
{% extends 'base_2.html' %} {% block content %}
<div class="info-wrapper">
  <div class="building-info">
    주소 : {{ building.location_str }} </br></br> 평점: {{ building.score }} / 5.0
    ({{building.buildingscore_set.count }}명 참여)
  </div>
  <div class="building-evaluates" style=" padding:40px;border-top:2px;height:200px;"> 
    {% for review in reviews %}
    <div class="building-review">
      {{ review.user.get_username }} : {{ review.content }}
    </div>
    {% endfor %}
  </div>
  {% comment %} <div class="link-evaluate"> {% endcomment %}
<div class="evaluateButton">
  <div class="evaluateButtonText">
      <a href="/building/{{ building.id }}/evaluate/">평가하러 가기</a>
    </div>
  </div>
</div>
{% endblock content %}

project/building/templates/building/evaluate.html
{% extends 'base_2.html' %}
{% load static %} 

{% block content %}
{% load static %} 

{% if error %}
<script type="text/javascript">
    alert("{{error}}");
</script>
{% endif %}

<div class="formWrapper">
<form action="/building/{{ building.id }}/evaluate/" method="POST">
    {% csrf_token %}
    <label for="review-score"> 건물 평가 점수 </label>
    <input id="review-score" type="number" name="review-score"> / 5 <br>
    </br>

    <label for="review-content"> 건물에 대한 평가를 해주세요 </label>
    </br>
    <input id="review-content" type="text" name="review-content"> <br>
    <input type="submit" value="작성" class="evaluateButton">
</form>

</div>

{% endblock content %}

project/building/templates/building/map.html
{% extends 'base_2.html' %}
{% block content %}{% load static %}


<div class="mapWrapper">
    <div class="mapTextWrapper">
        <input type="text" class="search" placeholder="건물 이름을 입력하세요" />
        <button id="map-search" onclick="changeLoc()">검색</button>
    </div>

<input type="hidden" class="search-value" value="논현로24길 41" />
<div id="map" style="width: 80%; height: 500px; margin: 0 auto;"></div>
</div>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="{% static 'building/map.js' %}"></script>
{% endblock%}
  </body>
 </html> 